name: 'sunglasshut_dbt'
version: '1.0.0'

profile: 'sunglasshut_dbt'

clean-targets:
  - "target"
  - "dbt_packages"

models:
  sunglasshut_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table
